name: flutter_file_view_example
description: Demonstrates how to use the flutter_file_view plugin.

publish_to: 'none'

version: 2.2.1+43

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_file_view:
    path: ../
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/files/
