name: flutter_file_view
description: A file viewer plugin for Flutter, support local file and network link of Android, iOS.
version: 2.1.0
homepage: https://github.com/LiWenHui96
repository: https://github.com/LiWenHui96/flutter_file_view
issue_tracker: https://github.com/LiWenHui96/flutter_file_view/issues

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.file.view
        pluginClass: FlutterFileViewPlugin
      ios:
        pluginClass: FlutterFileViewPlugin
